### ISSUE TITLE
Accent Color

### ISSUE THREAD

**Issue by itzTheMeow** [riivx/vendetta#17]
is there a way to change the accent color now that the individual files have been removed?

**Comment by riivx** [comment]
@itzTheMeow not right now, and i don't think anytime soon - maintaining more than 50 themes at once with all those changes discord loves to add is too hard.
but it's planned, and i would love to continue working on it, but i just know that i won't be able to maintain them all at once

**Comment by itzTheMeow** [comment]
is there a way to make a build script to generate theme files with each accent added? i think some other catp themes do that. i'm not sure how you're doing the accent colors though since it seems a lot of elements are different colors
